version: "3"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - ACCEPT_EULA = Y
      - MSSQL_SA_PASSWORD = dockeragp
    volumes:
      - dbdata:/data/db
    networks:
      - app-network
  expressjs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: express
    restart: unless-stopped
    env_file: .env
    environment:
      - PORT = $PORT
      - DATABASE_URL = $DATABASE_URL
    ports:
      - "4000:4000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    #command: /home/node/app/node_modules/.bin/nodemon app.js
networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
  node_modules:
