@api = http://localhost:4000/actividades
GET {{api}}
###
POST {{api}}
Content-Type: application/json

{
    "nombre": "AAA",
    "responsable_id": 1,
    "responsabilidad": "adasdasd",
    "descripcion": "ASDad",
    "archivo": null,
    "fecha_limite": "2022-02-04T00:00:00.000Z",
    "estado": "asdasd",
    "projects_id": 1
}

### get by id
GET {{api}}/2

### delete product 
DELETE {{api}}/3

### update
PUT {{api}}/2
Content-Type: application/json

{
    "nombre": "Tesssssst",
    "responsable_id": 1,
    "responsabilidad": "adasdasd",
    "descripcion": "ASDad",
    "archivo": null,
    "fecha_limite": "2022-02-04T00:00:00.000Z",
    "estado": "asdasd",
    "projects_id": 1
}