@api = http://localhost:3000/projects
GET {{api}}
###
POST {{api}}
Content-Type: application/json

{
    "modelo": "Proyecto",
    "nombre": "AGP",
    "responsable_id": 1,
    "prioridad": "Alta",
    "tipo": "Estandar",
    "responsabilidad": "Lider",
    "descripcion": "Aplicacion",
    "costo": 0,
    "archivo": null,
    "fecha_identificacion": "2022-12-01T00:00:00.000Z",
    "fecha_inicio": "2022-12-01T00:00:00.000Z",
    "fecha_cierre": "2022-12-01T00:00:00.000Z",
    "estado": "En desarrollo",
    "area_responsable": 1,
    "area_usuario": 2
}

### get by id
GET {{api}}/1002

### delete product 
DELETE {{api}}/1005

### update
PUT {{api}}/1011
Content-Type: application/json

{
    "modelo": "TEsttt",
    "nombre": "AGP",
    "responsable_id": 1,
    "prioridad": "Alta",
    "tipo": "Estandar",
    "responsabilidad": "Lider",
    "descripcion": "Aplicacion",
    "costo": 0,
    "archivo": null,
    "fecha_identificacion": "2022-12-01T00:00:00.000Z",
    "fecha_inicio": "2022-12-01T00:00:00.000Z",
    "fecha_cierre": "2022-12-01T00:00:00.000Z",
    "estado": "En desarrollo",
    "area_responsable": 1,
    "area_usuario": 2
}