@api = http://localhost:4000/trabajadores
GET {{api}}
###
POST {{api}}
Content-Type: application/json

{
    "nombre": "Palolo",
    "telefono": "1231241",
    "direccion": "Ate",
    "observaciones": "Promedio"
}

### get by id
GET {{api}}/2

### delete product 
DELETE {{api}}/1007

### get count
GET {{api}}/count

### update
PUT {{api}}/2
Content-Type: application/json

{
    "nombre": "Alets",
    "telefono": "1231241",
    "direccion": "Ate",
    "observaciones": "Promedio"
}