@api = http://localhost:4000/trabajadores
GET {{api}}
###
POST {{api}}
Content-Type: application/json

{
    "foto": null,
    "nombre": "Palolo Ramos",
    "telefono": "12313212",
    "direccion": "Test",
    "observacion": "12312",
    "sexo": "Masculino",
    "fecha_nacimiento": "2022-02-20T00:00:00.000Z",
    "fecha_ingreso": "2022-02-20T00:00:00.000Z",
    "fecha_cese": "2022-02-20T00:00:00.000Z",
    "categoria": "Empleado",
    "sede": "planta este",
    "area": "innovacion",
    "puesto": "pasante",
    "empresa": "precor"
}

### get by id
GET {{api}}/2

### delete product 
DELETE {{api}}/6

### get count
GET {{api}}/count

### update
PUT {{api}}/5
Content-Type: application/json

{
    "foto": null,
    "nombre": "Palolo Ramos",
    "telefono": "12313212",
    "direccion": "Test",
    "observacion": "12312",
    "sexo": "Masculino",
    "fecha_nacimiento": "2022-02-20T00:00:00.000Z",
    "fecha_ingreso": "2022-02-20T00:00:00.000Z",
    "fecha_cese": "2022-02-20T00:00:00.000Z",
    "categoria": "Empleado",
    "sede": "oeste",
    "area": "innovacion",
    "puesto": "pasante"
}